### ISSUE TITLE
Code indentation

### ISSUE THREAD

**Issue by pkingpi** [raspberrypilearning/rpg#10]
@MarcScott The indentation of the code is unorthodox: two spaces instead of the usual four. Can this be altered?

**Comment by MarcScott** [comment]
@pkingpi We will get around to altering this as we upgrade projects and replace screenshots of code with `actual code`. These are all screenshots from Trinket which unusually defaults to 2 spaces.
Can I suggest that the book doesn't use these images and instead just uses a monospaced font for the code and puts in the 4 spaces instead of 2.
